//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicket.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public string BookingId { get; set; }
        public string ShowId { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public System.DateTime BookingDate { get; set; }
    
        public virtual Shows Shows { get; set; }
    }
}
