//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicket.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedItems
    {
        public string BookingId { get; set; }
        public string FoodDrinkId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual FoodDrinks FoodDrinks { get; set; }
    }
}
